# Generated by Django 4.0.4 on 2022-05-28 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_blogmodel_fecha_creacion_alter_blogmodel_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
